language: node_js
node_js:
  - "6.3"
  - "6.0"
  - "5.11"
  - "5.2"
  - "5.0"
  - "4.4"
  - "4.0"
  - "0.12"
#last stable:
  - "iojs"
  - "node"
matrix:
  allow_failures:
    - node_js: "0.12"
    - node_js: "4.0"
    - node_js: "4.4"
    - node_js: "5.0"
    - node_js: "iojs"
os:
  - linux
before_install:
  - npm install -g grunt-cli
install:
  - npm install
script: grunt

# refs: https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Available-Versions