language: node_js
node_js:
  - "6"
  - "6.1"
  - "6.0"
  - "5.11"
  - "5.5"
  - "5.0"
  - "4.4"
  - "4.0"
  - "0.12.x"
  - "0.10.x"
  - "0.6"
#last stable:
  - "iojs"
  - "node"
os:
  - linux
before_install:
  - npm install -g grunt-cli
install:
  - npm install
script: grunt

# refs: https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Available-Versions